### ISSUE TITLE
The CakePHP top page has light grey text on white background

### ISSUE THREAD

**Issue by sampokuokkanen** [cakephp/cakephp.org#125]
The front page has light grey text on white background making it very hard to read. 

If you just remove `color: #C5C6C0; ` from `<blockquote>` it becomes much more readable. Though this makes the photos look a bit washed out in comparison, so maybe they could use some editing too. 

![Screenshot_2019-04-25 CakePHP - Build fast, grow solid PHP Framework Home](https://user-images.githubusercontent.com/22296618/56713148-e43ee700-676b-11e9-8d37-659540565cc8.png)

**Comment by kgbph** [comment]
I think it also applies to the company section. The background and logos do not contrast well.

![image](https://user-images.githubusercontent.com/22066281/56714449-67aa0980-6767-11e9-8460-ae792764b48b.png)

**Comment by davidyell** [comment]
Here is the standard,
https://www.w3.org/TR/WCAG20-TECHS/G18.html

**Comment by ADmad** [comment]
This is no longer an issue in the revamped site for Cake 4.
