### ISSUE TITLE
Questions about translation into Japanese

### ISSUE THREAD

**Issue by kamiyagunji** [cakephp/cakephp.org#135]
Hello.
I am a Japanese developer.
I would like to help with the translation, but is it okay to pull the modified code as usual and review it?

In case of Japanese translation, who should I review?

**Comment by markstory** [comment]
> I would like to help with the translation, but is it okay to pull the modified code as usual and review it?

Yes that would be great! I often use google translate to review translations, but perhaps there are others in the japanese community that can help with review as well?

**Comment by kamiyagunji** [comment]
> > I would like to help with the translation, but is it okay to pull the modified code as usual and review it?
> 
> Yes that would be great! I often use google translate to review translations, but perhaps there are others in the japanese community that can help with review as well?

Is it all right to check the corrections and leave a trail?
If that is the case, I would like to rely on the members of my company who took the stage at Cakefest 2019.
Is it okay to have him check the corrections and leave a comment?

**Comment by markstory** [comment]
> Is it all right to check the corrections and leave a trail?

Yes, feel free to make as many pull requests as you need.

>  Is it okay to have him check the corrections and leave a comment?

Yes that works for me :+1:

**Comment by chinpei215** [comment]
When I translated this page, I didn't translate the section intentionally, as I thought I would need to get permission to translate their words if I translate it. But if there is no such problems, it is nice idea.

**Comment by kamiyagunji** [comment]
> When I translated the page, I didn't translate the section intentionally, as I thought I would need to get permission to translate their words.

When I translate, I will make sure that there is no problem with the translation.

**Comment by ifuriito** [comment]
Hello.
I am a Japanese developer.
I work for Lancers as a developer.
I will translate together.
