### ISSUE TITLE
Why isn't the translation not working?

### ISSUE THREAD

**Issue by kamiyagunji** [cakephp/cakephp.org#136]
I learned that there are some parts that are not translated into Japanese.

However, when you look at the source code, the code that was actually translated was present. 

Is this a bug? Or is it set to prevent translation in other parts?

↓Although these are written in Japanese, the translation is not working.
```
#: Template/Element/home/summary.ctp:135
msgid "CakePHP comes with built-in tools for input validation, CSRF protection, Form tampering\n\t\t\t\t\t\t\tprotection, SQL injection prevention, and XSS prevention, helping you keep your application\n\t\t\t\t\t\t\t{0}."
msgstr "CakePHPにはアプリケーションを{0}に保つ手助けになる入力検証、CSRF防止、フォーム偽造防止、SQLインジェクション対策、そしてXSS対策のための組み込みのツールが付いています。"
```
<img width="1379" alt="スクリーンショット 2019-11-09 19 23 01" src="https://user-images.githubusercontent.com/37334454/68527098-944df900-0326-11ea-9f83-adebf5089763.png">

It seems that there is a link in the untranslated part.
Is that why translation doesn't work?

**Comment by garas** [comment]
String was updated. Regenerate .pot and translate new string.

**Comment by markstory** [comment]
You can also double check that the msgid still matches what is in the templates and that the templates are using `__()` for that content.

**Comment by yeliparra** [comment]
Fixed msgid. Thanks for reporting this!
