### ISSUE TITLE
Typography for header tags could be improved

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp.org#148]
Using font weight of 200 for header tags isn't too nice IMO. Here's my suggested change:

Before
![Screenshot_2020-01-28 CakePHP - Build fast, grow solid PHP Framework Home](https://user-images.githubusercontent.com/142658/73265786-9c1d8b00-41fb-11ea-8bcf-77c218264fce.png)

After 
![Screenshot_2020-01-28 CakePHP - Build fast, grow solid PHP Framework Home(1)](https://user-images.githubusercontent.com/142658/73265796-a0e23f00-41fb-11ea-8060-70adfecb622d.png)

It basically removed the font-weight 200 overriding for all header tags and uses font-weight bold for "New CakePHP 4.0 Strawberry.". I can a PR if people like the change.

**Comment by yeliparra** [comment]
Changes were applied, now it's looking much better! Thank you for the suggestion.
