### ISSUE TITLE
Css class `sidebar-2` overlaps newsletter

### ISSUE THREAD

**Issue by challgren** [cakephp/cakephp.org#156]
On the following pages if you scroll to the bottom the sidebar will cover up the newsletter spot and make it pretty difficult to enter info into it.

https://cakephp.org/pages/business-solutions
https://cakephp.org/pages/get-involved

![Screenshot 2020-02-26 23 03 00](https://user-images.githubusercontent.com/88909/75413941-9bf0d800-58ec-11ea-998b-cdd00ea8134c.png)
![Screenshot 2020-02-26 22 41 37](https://user-images.githubusercontent.com/88909/75413947-9dba9b80-58ec-11ea-96cd-42f50a1e76e0.png)

**Comment by CakeDCTeam** [comment]
We will check this, thank you for the feedback
