### ISSUE TITLE
Website: newsletter?

### ISSUE THREAD

**Issue by call-me-matt** [cakephp/cakephp.org#157]
This concerns the website of CakePHP... don't know where to post it else:
The [newsletter](https://cakephp.org/pages/newsletter) page is not working for me (Ubuntu, Firefox 74.0 64-Bit) - it is just showing an empty page. I would be interested to sign up, though...

**Comment by saeideng** [comment]
works for me

**Comment by othercorey** [comment]
Can you post a screenshot or check for errors and post them?

**Comment by call-me-matt** [comment]
OK, looking at the error messages, I realized that it was my adblocker.
Sorry
