### ISSUE TITLE
Empty meetups page.

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp.org#165]
When there are no upcoming meetups the https://cakephp.org/pages/meetups page is pretty blank.

It would be nice to show a placeholder like "Stay tune for next...".

**Comment by yeliparra** [comment]
Added message.

Thank you,

**Comment by othercorey** [comment]
I think we could show events within the past 6hrs or day maybe. I tried to find the meetup for one that just started and it was blank.
