### ISSUE TITLE
Newsletter Archive isn't up-to-date?

### ISSUE THREAD

**Issue by drtrppr** [cakephp/cakephp.org#172]
People who don't (want to) subscribe to the newsletter, or don't (want to) use twitter/facebook, don't have easy access to the info. 

Moreover, it somehow gives the impression the site is dead (when page cannot be maintained, maybe it's better to delete it).

**Comment by yeliparra** [comment]
You can find the newsletters here https://cakephp.org/pages/newsletter. 

Thanks,
