### ISSUE TITLE
Review sites listed under Showcase

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp.org#173]
There have been posts on our forum stating that many of the sites listed under showcase don't seem to be using CakePHP. So can someone from CakeDC please review and update the showcase page or respond to the forum posts as appropriate.

https://discourse.cakephp.org/t/update-to-sainsburys-bank-on-cakephp-showcase/8346
https://discourse.cakephp.org/t/update-to-debtor-daddy-on-cakephp-showcase/8347
https://discourse.cakephp.org/t/update-to-blendtec-on-cakephp-showcase/8345

**Comment by yeliparra** [comment]
@ADmad projects has been updated in showcase page.
