### ISSUE TITLE
RFC: Create a new and nice IRC log

### ISSUE THREAD

**Issue by ravage84** [cakephp/cakephp.org#26]
@ionas  reported in cakephp/docs#4045:
Found this by accident on some github posts:
https://botbot.me/freenode/gratipay/2013-10-16/?msg=6935850&page=1
The old log interface could be made available as an archive.

**Comment by ADmad** [comment]
We already have a new and nice IRC logging now, it's called Slack :P

**Comment by ADmad** [comment]
I believe https://github.com/cakephp/cakebot is the repo for code that powers irc.cakephp.org

**Comment by yeliparra** [comment]
I agree with @ADmad , we have slack.
