### ISSUE TITLE
Banner menu not unified

### ISSUE THREAD

**Issue by ravage84** [cakephp/cakephp.org#31]
The banner menu isn't unified, on some pages it contains different menu items
On the bakery page for example, it includes "Cakesf" under community, while on other pages it does not.

**Comment by markstory** [comment]
@ravage84 I've working on the menus across the sites. Unfortunately there isn't a good way to share menu links between all the sites as they are all implemented in totally different technologies/tools, so its a lot of manual work.  bakery.cakephp.org no longer has a link to CakeSF, and should match the API/main site now.

**Comment by ravage84** [comment]
I see...
I think in the past we had a separate repo for the main navbar. That isn't a viable solution (anymore)?

**Comment by markstory** [comment]
@ravage84 The separate repo didn't ever really *work*. It half worked, but not really.
