### ISSUE TITLE
Lot of outdated & missing stuff on "Get Involved"

### ISSUE THREAD

**Issue by ravage84** [cakephp/cakephp.org#33]
- [x] User Support
	- [x] should list the slack channel
- [ ] Education and Training
	- [ ] should list PHP Mentoring https://app.phpmentoring.org/
- [ ] Marketing and Evangelism
	- [ ] Should list a mail address to get help for people interested in getting a new local group started
- [x] Contributing Code
	- [x] "Contributing via Patch Files"
		- [x] Do we really still want people to provide it that way?
	- [x] Contributing via Commits on a GitHub Fork
		- [x] Should have a link to the GH repo
- [ ] Testing and Quality Assurance
	-  [x] New Issues That Need Triaging
		- [x] Only core team member have the necessary rights to tag issues and PRs!
	- [ ] Features and Enhancements for Future Releases
		- [ ] The whole paragraph seems to be totally outdated, I would remove it.
- [x] Translations
	- [x] Should be included into Documentation as translating the API does not make sense
- [ ] Get Help
	- [ ] The get help sections from the 2.x and 3.x cookbook should be merged with this into one centralized location, because of redundancy and risk of getting out of date/out of sync:
	- http://book.cakephp.org/2.0/en/cakephp-overview/where-to-get-help.html
	- http://book.cakephp.org/3.0/en/intro/where-to-get-help.html

**Comment by markstory** [comment]
I can work on getting this fixed.

**Comment by ravage84** [comment]
@megslalk how do you feel about this:
> Marketing and Evangelism 
> Should list a mail address to get help for people interested in getting a new local group started

Since this is about your job :smirk_cat:

**Comment by yeliparra** [comment]
Get Involved page was updated. 

Closing this!
