### ISSUE TITLE
Translate new website into French

### ISSUE THREAD

**Issue by ravage84** [cakephp/cakephp.org#35]
@cake17 would you be interested into translating the new website into french? Just like the japanese guys? See https://github.com/cakephp/cakephp.org/pull/34

**Comment by HavokInspiration** [comment]
I can give a hand if needed.
ping @antograssiot as well 😄

**Comment by cake17** [comment]
Yes we can translate it, good idea

**Comment by antograssiot** [comment]
if I'm not mistaken, @chinpei215 work is to get cakephp.jp a translated copy of cakephp.org

I saw that cakephp.fr is already taken/used, do you have any contact with its owner ?

**Comment by ravage84** [comment]
According to WHOIS:

````
Résultat de votre recherche

    Nom de domaine : cakephp.fr
    État : Actif (consulter aussi le site web )
    DNSSEC : inactif
    Bureau d'enregistrement : OVH
    Date de création : 22 novembre 2011 21:42
    Date d'expiration : 22 novembre 2016 21:42
    Serveurs de noms (DNS)
        Serveur n° 1: dns.ovh.net
        Serveur n° 2: ns.ovh.net

Titulaire : PERGOD ERWAN

    PERGOD ERWAN
        les Combes
        74450 Saint Jean de Sixt
        France

Téléphone :+33 6 86 52 90 37

Courrier électronique :erwanpergod@gmail.com

Joignabilité :NotIdentified

Eligibilité :NotIdentified
Contact administratif : PERGOD ERWAN

    PERGOD ERWAN
        les Combes
        74450 Saint Jean de Sixt
        France

Téléphone :+33 6 86 52 90 37

Courrier électronique :erwanpergod@gmail.com

Joignabilité :NotIdentified

Eligibilité :NotIdentified
Contact technique : OVH NET

        OVH
        140, quai du Sartel
        59100 Roubaix
        France

Téléphone :+33 8 99 70 17 61

Courrier électronique :tech@ovh.net

Joignabilité :NotIdentified

Eligibilité :NotIdentified

````

**Comment by ravage84** [comment]
Stupid me, I don't think http://www.cakephp.fr ir really relevant.

May be replace/adapt http://www.cakephp-fr.org/ instead?

**Comment by antograssiot** [comment]
@ravage84 I saw the whois,  my quest on was more does anyone know him or is already in contact with him.
I don't think that cakephp-fr.org is a good choice either.

**Comment by cake17** [comment]
@antograssiot this belongs to someone I can contact. The [cakephp-fr.org](https://github.com/cakephp-fr/cakephp-fr.github.io) needs to be reorganized or removed. I guess that now that the discourse forum exists, the website can only follow the english official website.

I can tell people of the french forum to migrate to the official discourse forum. Would it be possible to create a dedicated topic for the french language on discourse ?

**Comment by ravage84** [comment]
@cake17 I'm not a discourse specialist but it seems there is no functionality for a sub forum. Only a specific category could be created for French topics, but I'm not sure this would really suffice.
So I'm not sure if you will be happy after migrating the French speaking people to the new forum...

**Comment by cake17** [comment]
I guess we'll keep the cakephp-fr forum but we can also translate this website in french for people localized as french.

Could someone add the pot file to translate ? I tried to ``composer install`` and extract the pot but some plugins need authorization.

**Comment by cake17** [comment]
#53 is up now, this issue can be closed
