### ISSUE TITLE
Homepage carousel doesn't stretch

### ISSUE THREAD

**Issue by davidyell** [cakephp/cakephp.org#36]
If you are viewing the website on a high resolution screen the carousel doesn't stretch to fit across the page leaving a white block on the right hand side of the page.

You end up with this, http://i.imgur.com/tttmziI.png

**Comment by h-ibaldo** [comment]
Setting the width attribute to 100% inside the image tag should fix the problem:
![captura de tela 2016-06-10 22 08 22](https://cloud.githubusercontent.com/assets/19846942/15982397/9ed5519e-2f5c-11e6-86b1-967ab497b3f5.png)

**Comment by yeliparra** [comment]
Pull request merged and deployed in live
