### ISSUE TITLE
Auto deploy not triggered after push

### ISSUE THREAD

**Issue by yeliparra** [cakephp/cakephp.org#40]

**Comment by josegonzalez** [comment]
I'll actually set myself as the person here, since we want to move this to the new server.

Do we have a database somewhere that I can get access to which I can migrate over as well?

**Comment by steinkel** [comment]
I left a dump in the current server, /home/deploy/cakephp.sql.gz

You should have access to it via `ssh 23.253.215.107 -l deploy`

**Comment by yeliparra** [comment]
This was already done  by @steinkel.
