### ISSUE TITLE
Docs CSS letter-spacing issue

### ISSUE THREAD

**Issue by cornellsteven** [cakephp/cakephp.org#45]
Maybe this was the intended effect, but at some point `letter-spacing: 0.01em` was added to `body`, which is fine for all of the body copy, but – at least for me – this makes the code snippets look very strange and / or more difficult to read. It almost has the appearance of being an "extended" version of a font.

When the new look and and feel was updated a couple weeks ago (which I love), this was the first thing I noticed. I thought it was just a weird font, but then I saw that it was Roboto, which I like, which lead to snooping around to find the letter-spacing issue.

If this is a personal thing, and everybody else likes it, I'll just fix it with a quick userscript or extension or something, but I thought perhaps it was a mistake, so figured I'd add an issue just in case I'm not the only one.

**Comment by ADmad** [comment]
`body` has letter-spacing set to `0.05em` (on api and book) not `0.01em` as you state. Did you make a typo or you are seeing an older cached css?

If you feel `0.05em` spacing for code snippets isn't optimal what change do you propose to improve it?

**Comment by cornellsteven** [comment]
Sorry, I should have said that. On my browser, I just reset it back to `normal`, and it looks much better to me.

**Comment by ADmad** [comment]
Thank you for your feedback, we will take under consideration the change you propose.

**Comment by markstory** [comment]
I'll change the letter-spacing on the `pre` blocks to normal. I agree it looks better.

**Comment by markstory** [comment]
Closing as I've updated the various book versions and the API.

**Comment by cornellsteven** [comment]
@ADmad that totally was a typo on my part. My bad!

@markstory Thanks!
