### ISSUE TITLE
Line heights in titles are too tight for multi-line titles.

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp.org#46]
The title line-height could use with some increases as multi-line titles get a bit jumbled.

![screen shot 2016-06-13 at 21 27 28](https://cloud.githubusercontent.com/assets/24086/16028487/d16064c0-31ad-11e6-9d47-f0d65cf62c84.png)

This issue doesn't show up on the book

**Comment by pedrofs** [comment]
Hi @markstory 

I couldn't find this issue.

I checked here:
![cakephp_org_01](https://cloud.githubusercontent.com/assets/56484/16811898/ebcdf222-4900-11e6-8d8c-17f933e56749.png)

Here:
![cakephp_org_02](https://cloud.githubusercontent.com/assets/56484/16811907/f58b3306-4900-11e6-8c38-f530dd5f4758.png)

And here:
![cakephp_org_03](https://cloud.githubusercontent.com/assets/56484/16811911/fa819b5c-4900-11e6-8483-7cf7ff452932.png)

**Comment by markstory** [comment]
I can't reproduce anymore either.
