### ISSUE TITLE
email validation rule seems to reject correct emails

### ISSUE THREAD

**Issue by 2ndGAB** [cakephp/cakephp.org#49]
Hello,

I currently have few emails, successfully verified by verify-email.org, which are rejected by the validation rule.  
Between others:  
tourisme.coeurmedoc@orange.fr
info@parc-landes-de-gascogne.fr
office-tourisme.soule@wanadoo.fr  

Any idea?

**Comment by ADmad** [comment]
Wrong repo. Please reopen on cakehp/cakephp repo.

**Comment by 2ndGAB** [comment]
Oups ak Admad
