### ISSUE TITLE
Include a language selector at the top bar

### ISSUE THREAD

**Issue by yeliparra** [cakephp/cakephp.org#55]

**Comment by ravage84** [comment]
It should list:

- English (Default)
- French (WIP)
- Japanese

Refs: https://github.com/cakephp/cakephp.org/pull/39 https://github.com/cakephp/cakephp.org/pull/53

**Comment by chinpei215** [comment]
Also it would be better to use hreflang in HTML header or HTTP header, for SEO reasons.
https://support.google.com/webmasters/answer/189077

**Comment by yeliparra** [comment]
Included language selector, French was not included in the list because there are just few text translated.
