### ISSUE TITLE
Adding CakePHPJobs.com to the community menu?

### ISSUE THREAD

**Issue by burzum** [cakephp/cakephp.org#62]
Can we add it there?

If somebody has further suggestions I'm glad to hear them. I'll deploy an update this week that will add more options like salary and a few more details.

Update: Added the salary option to the site.

**Comment by andtxr** [comment]
@burzum Is CakePHPJobs.com ready to i18n?

**Comment by burzum** [comment]
@andtxr I would go over it but I've used the translation functions almost everywhere.

**Comment by andtxr** [comment]
@burzum Nice. Let me know when it is ready so I can provide the pt_BR pot file. I really liked the project.

**Comment by burzum** [comment]
PR is up https://github.com/cakephp/cakephp.org/pull/63
