### ISSUE TITLE
Website on 90°-flipped monitor

### ISSUE THREAD

**Issue by 3811015** [cakephp/cakephp.org#71]
Hi,

My screen resolution is 1200x1920.

This is how cakephp.org looks like on my high screen.
![image](https://cloud.githubusercontent.com/assets/19705939/19476710/f8fb932e-953a-11e6-8776-0a6f2a93a0fe.png)

This is what it should look like (and does look like on the wide screen)
![image](https://cloud.githubusercontent.com/assets/19705939/19476723/0c5f4488-953b-11e6-9b02-947b5002dcce.png)

It is really annoying to get into the API or cookbook, to drag the browser around to the other screen and back. I wouldnt bother so much about the cake not beeing displayed, but getting the 2 links back would really help a lot.

Thank you in advance.

**Comment by 3811015** [comment]
@ADmad Thank you ;)

**Comment by yeliparra** [comment]
Deployed in live!

Thank you guys. @ADmad @3811015

**Comment by 3811015** [comment]
@yeliparra Sorry to disappoint you, I can't see any improvement.

**Comment by yeliparra** [comment]
@3811015 I just made a minor adjustment. Could you try again?

**Comment by 3811015** [comment]
Well it looks like first its displayed well and then after 200 ms the language selection flips to the next line.

**Comment by yeliparra** [comment]
I am not able to reproduce it. I am resizing the browser till get the hamburger menu icon and I don't get two lines menu in any resolution. Did you clean cache?

@3811015 Which browser are you using? and resolution?

@ADmad Are you able to reproduce it?

**Comment by 3811015** [comment]
Its same in chrome and firefox. Screen resolution is 1200 x 1920 (the monitor is raised on edge)

**Comment by 3811015** [comment]
I would love to upload a screen video to share the experience with this... but this isn't accepting video here...

**Comment by phpnut** [comment]
@3811015 can you upload to dropbox or another hosting service?

**Comment by 3811015** [comment]
I am not registered with most of this cloud stuff.

**Comment by josegonzalez** [comment]
imgur works fine for image uploads.

**Comment by phpnut** [comment]
@3811015 try to email it to me @ phpnut@cakephp.org

**Comment by 3811015** [comment]
@phpnut 21.2 MB

**Comment by 3811015** [comment]
Lets try it this way. https://ufile.io/7a57
30 days...
@phpnut @josegonzalez

**Comment by phpnut** [comment]
@3811015 I was able to download it. We will see if we are able to fix the issues.

**Comment by yeliparra** [comment]
@3811015 I have not been able to reproduce it even after watching the video. 

Could you help us and provide a PR with the fix?

**Comment by yeliparra** [comment]
Closing this since we were not able to reproduce it and no more activity for a long time
