### ISSUE TITLE
Stop hijacking the scroll

### ISSUE THREAD

**Issue by martinbean** [cakephp/cakephp.org#75]
I’m a longtime computer user. I’ve done a fair bit of scrolling in my time. I know how to do it, how “aggressively” to flick my mouse to get to roughly where I want on a web page.

Unfortunately, http://cakephp.org doesn’t believe I can. Trying to use the site is _annoying_ as it seems to override the scroll speed/distance from my operating system’s defaults. This is bad UX.

Can you remove whatever JavaScript plugin it is “hijacking” the scroll speed/distance and give control back to me, the user, please?

**Comment by josegonzalez** [comment]
@markstory @phpnut didn't we already remove scrolljacking before? I remember that being feedback we gave to the designer during the rebranding process.

**Comment by phpnut** [comment]
@josegonzalez  @markstory yes, I do not notice it on the main site.

**Comment by martinbean** [comment]
@josegonzalez @phpnut I’m going to take a guess it’s “SmoothScroll” in this file: https://cakephp.org/cache_js/public.js

**Comment by yeliparra** [comment]
Closing because of obsolete.
