### ISSUE TITLE
Add a donate button

### ISSUE THREAD

**Issue by ADmad** [cakephp/cakephp.org#76]
There should be a "donate" button somewhere on the site on the off chance that someone feels generous :)

The old cakefoundation.org has it but I don't think anyone even knows that site exists or how to reach it.

**Comment by phpnut** [comment]
Donate button added to https://cakephp.org

**Comment by ravage84** [comment]
Good idea, but we probably should explain where these donations go (probably the foundation) and may be even what (normally) will be done with tit (part of financing the CakeFest)?

This will ensure people have _some_ certainty where their money goes.
