### ISSUE TITLE
Mistaken list of services provided

### ISSUE THREAD

**Issue by andtxr** [cakephp/cakephp.org#79]
The list of providen services is actually a duplicate of the course topics one.

https://cakephp.org/pages/business-solutions

I have created this issue to reference it in a big upcoming PR.

I am fixing it right now.

**Comment by josegonzalez** [comment]
That ends up redirecting to the irc site for me, are you sure the DNS is pointed at the right thing?

@phpnut may be worth repurposing a different domain for staging sites.

**Comment by andtxr** [comment]
@josegonzalez my bad.

This is my local vhost.

https://cakephp.org/pages/business-solutions

**Comment by steinkel** [comment]
List of services and training topics fixed in #80, thanks
