### ISSUE TITLE
Videos page has big blank banner

### ISSUE THREAD

**Issue by ravage84** [cakephp/cakephp.org#86]
On the [videos](https://cakephp.org/documentation/videos) page, I get a big blank banner section between the banner navigation and the page title.

With recent Firefox and Chrome.

![videos-page](https://cloud.githubusercontent.com/assets/625761/22881654/e06f6934-f1e7-11e6-9198-9aef4ed4b4d5.png)

**Comment by yeliparra** [comment]
Fixed and deployed in live!
