### ISSUE TITLE
Videos page loading issues

### ISSUE THREAD

**Issue by ravage84** [cakephp/cakephp.org#88]
The [videos](https://cakephp.org/documentation/videos) page takes quite some time to load.
It seems there are some issues.

Sometimes it fails to load embeded stuff from youtube:

![videos-page-failed-loads](https://cloud.githubusercontent.com/assets/625761/22881901/e32bb316-f1e8-11e6-9327-271fd82395b8.png)

Other times, it never ends trying to load them:

![videos-page-neverending-loads](https://cloud.githubusercontent.com/assets/625761/22881912/ef689978-f1e8-11e6-997b-9d0db96342be.png)

**Comment by ravage84** [comment]
Could it be, that the page loads all embeded videos, even the ones that are initially hidden by the "Load More" button?

**Comment by andrej-griniuk** [comment]
There are 12 + 1 videos shown on the page straightaway so there request are for them. The other videos are not loaded before you click "Load More".
